### PR TITLE
Fix options not found error

### PR DESCRIPTION
**Pull request by sebirdman**
Looks like this got missed. Made it impossible to getUser info

### CODE REVIEW

**Comment by hzalaz** [comment]
@sebirdman what was the error you were getting?

**Comment by sebirdman** [comment]
```
6-16 12:56:15.548 20196 21586 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
06-16 12:56:15.548 20196 21586 W ReactNativeJS: ReferenceError: Can't find variable: options
06-16 12:56:15.548 20196 21586 W ReactNativeJS: users@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:94449:29
06-16 12:56:15.548 20196 21586 W ReactNativeJS: _callee3$@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:94320:47
06-16 12:56:15.548 20196 21586 W ReactNativeJS: tryCatch@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:20190:44
06-16 12:56:15.548 20196 21586 W ReactNativeJS: invoke@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:20378:30
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:20215:28
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:94217:75
06-16 12:56:15.548 20196 21586 W ReactNativeJS: tryCallTwo@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:19554:7
06-16 12:56:15.548 20196 21586 W ReactNativeJS: doResolve@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:19693:23
06-16 12:56:15.548 20196 21586 W ReactNativeJS: Promise@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:19575:12
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:94197:36
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:94309:25
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:54716:24
06-16 12:56:15.548 20196 21586 W ReactNativeJS: dispatch@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:54661:27
06-16 12:56:15.548 20196 21586 W ReactNativeJS: _callee2$@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:94294:37
06-16 12:56:15.548 20196 21586 W ReactNativeJS: tryCatch@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:20190:44
06-16 12:56:15.548 20196 21586 W ReactNativeJS: invoke@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:20378:30
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:20215:28
06-16 12:56:15.548 20196 21586 W ReactNativeJS: fulfilled@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:94200:36
06-16 12:56:15.548 20196 21586 W ReactNativeJS: tryCallOne@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:19546:14
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:19632:25
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:5770:24
06-16 12:56:15.548 20196 21586 W ReactNativeJS: callTimer@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:2101:17
06-16 12:56:15.548 20196 21586 W ReactNativeJS: callImmediatesPass@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:2187:36
06-16 12:56:15.548 20196 21586 W ReactNativeJS: callImmediates@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:2197:48
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1968:48
06-16 12:56:15.548 20196 21586 W ReactNativeJS: __guard@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1956:11
06-16 12:56:15.548 20196 21586 W ReactNativeJS: __callImmediates@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1967:19
06-16 12:56:15.548 20196 21586 W ReactNativeJS: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1870:32
06-16 12:56:15.548 20196 21586 W ReactNativeJS: __guard@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1956:11
06-16 12:56:15.548 20196 21586 W ReactNativeJS: invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false:1868:19
06-16 12:56:15.548 20196 21586 W ReactNativeJS: invokeCallbackAndReturnFlushedQueue@[native code]

```

**Comment by hzalaz** [comment]
Nevermind, thought it was in a different file the change and now I see the issue

**Comment by hzalaz** [comment]
@sebirdman thanks, there is a new release with that fix

**Comment by sebirdman** [comment]
@hzalaz awesome, thanks for being so responsive

**Pull request merged**
