### PR TITLE
passwordLessStart added to auth #154

### PR DESCRIPTION
**Pull request by bartolkaruza**
[x] Implement
[x] Test email link
[ ] Add unit test
[ ] Test sms code/link + email code
[ ] Add method to doc

### CODE REVIEW

**Comment by cocojoe** [comment]
The current guidance to use Passwordless is customise your `Hosted Page` in the [Auth0 Dashboard](https://manage.auth0.com/#/login_page) to use `Lock (Passwordless)` and use the code method.

**Comment by bartolkaruza** [comment]
The passwordLess API endpoint is supported and the web SDK includes both code and link methods. What is the risk of exposing this method which is basically a post request to an unauthenticated endpoint, using the client ID which is already bundled in the app anyway?

**Comment by cocojoe** [comment]
How are you expecting to use it? You send a code, what next?

**Comment by bartolkaruza** [comment]
What I'm trying to do is the following: *app* user enters email > *app* post request to passwordlessStart > *app* Check your email message
*email* click on link > *browser* passwordless confirm page > *browser* redirect to callback > *app* open deeplink

**Comment by bartolkaruza** [comment]
@cocojoe Any thoughts on this approach?

**Comment by cocojoe** [comment]
I don't think it will work, what endpoint do you intend to send the OTP to in your deep link?

**Comment by navinag** [comment]
Can the same API used by web JS SDK be used to verify the code sent using passwordless. 
/passwordless/verify , be used in native to add passwordless workflow?
@cocojoe thoughts?

**Pull request closed without merging**
