### PR TITLE
Fix iOS module import for Expo SDK 44

### PR DESCRIPTION
**Pull request by Bardiamist**
>From https://github.com/expo/expo/issues/15622#issuecomment-997225774, the double-quoted react header imports will break building on Expo SDK 44. The double-quoted imports should be for react-native < 0.40. as nowadays react-native uses CocoaPods, it should be safe to use the angle-bracket import.

### CODE REVIEW

**Comment by codebutler** [comment]
@evansims How can we help get this merged and released?

**Comment by poovamraj** [comment]
Hey all, We are seriously considering supporting Expo in our project. We will look into this PR soon but it requires some internal discussion that we have already started. I will keep you updated on this and try to provide an update soon. Sorry for the delay!

**Review by Widcket — APPROVED** [review]

**Comment by stevewillard** [comment]
Oh my - if this could make it into a new `react-native-auth0` release, that would be amazing! ❤️ 🙏

**Comment by Bardiamist** [comment]
This fix for bare react native projects with Expo. Not for Expo projects.

**Pull request merged**
