### PR TITLE
[SDK-3598] RNA sample app

### PR DESCRIPTION
**Pull request by poovamraj**
### Changes
- Added a sample app to the repo
- Moved React Native to a peer dependency (this caused linking issue in sample app)
- Fixed a parameter error in webauth/index.js
- This is done by using https://github.com/callstack/react-native-builder-bob

### Testing
- [x] This change adds unit test coverage
- [x] This change has been tested on the latest version of the platform/language or why not

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
@poovamraj How should I build, configure and run the sample? That info would be good to see in the readme as well for others.

**Comment by poovamraj** [comment]
@stevehobbsdev I created a seperate README inside the example folder, this way we can avoid novice users from getting confused because of the example application guide

**Comment by stevehobbsdev** [comment]
I've got a few issues running the sample on iOS according to the instructions:

image

**Review by stevehobbsdev — CHANGES_REQUESTED** [review]
As mentioned on our call to resolve the above (thank you!) I would just tweak the readme:

* Command to run should be `yarn example ios|android`
* Let's see if we can consolidate all the `yarn` commands down to just one or two
* Let's include a short section in the readme on where to go to configure with my own tenant - great that it has a default though

**Comment by poovamraj** [comment]
Hey @stevehobbsdev great feedback. I have implemented them. I have left `bootstrap` and `prepack` as it is instead of merging it as they are lifecycle commands that come inbuilt and I feel it is better to leave them as it is.

**Comment by poovamraj** [comment]
This PR will improve the test coverage - https://github.com/auth0/react-native-auth0/pull/652. As we have done the native code migration unit tests there

**Review by stevehobbsdev — APPROVED** [review]

**Comment by poovamraj** [comment]
As mentioned before,  This PR will improve the test coverage - https://github.com/auth0/react-native-auth0/pull/654. As we have done the native code migration unit tests there.

**Review by stevehobbsdev — APPROVED** [review]

**Pull request merged**
