### PR TITLE
Returning credentials at authorize

### PR DESCRIPTION
**Pull request by guhcostan**
### Changes
I changed the authorize method to return the credentials, because it is on documentation but the code is not.

### Testing

- [] This change adds unit test coverage
- [X] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] All existing and new tests complete without errors
- [X] All active GitHub checks have passed

### CODE REVIEW

**Comment by poovamraj** [comment]
Hey @guhcostan, thanks for this PR. We are planning to do something similar in our next release as well. Can you add some unit tests to check the returning value and also point it to vnext?

**Review by poovamraj — CHANGES_REQUESTED** [review]
Hey @guhcostan, thanks for this PR. We are planning to do something similar in our next release as well. Can you add some unit tests to check the returning value and also point it to vnext?

**Comment by poovamraj** [comment]
Hi @guhcostan, we are implementing this change as a part of our v3 initiative. Feel free to direct this branch towards that or we will be happy to implement the required changes as we are actively working on this initiative.

**Comment by guhcostan** [comment]
Please @poovamraj implement yourselves then. I couldn't run the project to do the tests, I'm sorry. I will close the PR.

**Pull request closed without merging**
