### PR TITLE
Close Browser app tab after finishing Auth

### PR DESCRIPTION
**Pull request by cocojoe**
Tested in Chrome 61
#87

### CODE REVIEW

**Comment by cocojoe** [comment]
@lbalmaceda can you take a look at this first please.

**Comment by lbalmaceda** [comment]
Seems fine. You should also try it without Chrome so it opens the link in a Browser instead of a Custom Tab. Btw, we don't have tests for this?

**Comment by cocojoe** [comment]
I tried in browser, didn't work in the one I tested. RNA has tests but the platform specific stuff doesn't. Probably a bit of work to setup a CI that is testing JS/Android/iOS.

**Comment by hzalaz** [comment]
I'd not do that to keep this simple. The native code should be minimal

**Pull request merged**
