### PR TITLE
Initialized flag on useAuth0 hook

### PR DESCRIPTION
**Pull request by cranberyxl**
### Changes

Add `isInitializing` flag to `useAuth0`. This is true until we know that a user is either logged in or logged out. This allows us to prevent showing the logged in or logged out state of an app incorrectly while the `user` is returned from the `CredentialsManager`. 

### Testing

```js
const MyComponent = () => {
  const { isInitializing, user } = useAuth0();

  if (isInitializing) {
    return <Text>Auth0 is initializing</Text>;
  }

  return <Text>User is logged { user ? 'in' : 'out' }</Text>;
}
```

- [x] This change adds unit test coverage
- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] All existing and new tests complete without errors
- [x] All active GitHub checks have passed

### CODE REVIEW

**Comment by poovamraj** [comment]
@cranberyxl I guess this can be achieved by checking both `user` object and `error` object by checking if one in both of them are initialized. Is there any other particular scenario I am missing out?

**Comment by cranberyxl** [comment]
There is the time before the first request has completed, where there is no user and no error, while the first calls are being made to credentials manager, etc. This is indistinguishable from there is no user and no error and we've checked credentials manager.

**Comment by DannyBiezen** [comment]
This is something I've been wanting as well. It would help cleanup some of the current authentication logic in my components

**Review by poovamraj — COMMENTED** [review]
Hi @cranberyxl, this would be a great addition indeed. Can you use our [auth0-react](https://github.com/auth0/auth0-react/blob/master/src/reducer.tsx) as inspiration and make the following changes?

- Rename the state to `isLoading`
- Set it to `false` when the user is loaded from Credentials Manager or Login
- Set it to `false` when there is an error
- Set it to `true` when the Login is started again.

**Comment by gradisarjoze** [comment]
Anyone with any workarounds at the moment?

**Comment by poovamraj** [comment]
Hi everyone, thanks a lot for the contribution. We have made a few more refactors and improvements to this PR. Please feel free to let us know your feedback on this. Thanks!

**Review by cranberyxl — COMMENTED** [review]
Looks good to me

**Comment by cjpete** [comment]
Looks great. It would be great to see a similar PR to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-auth0 to keep the two in sync

**Comment by poovamraj** [comment]
@cjpete Great catch. Any possibility you can help us with it?

**Comment by cranberyxl** [comment]
@poovamraj I think `isInitializing` is a more semantically correct name as the flag is only changed once. If new requests are made it does not flip back to `true`

**Review by frederikprijck — APPROVED** [review]

**Comment by frederikprijck** [comment]
@cranberyxl It was decided to go with `isLoading` for consistency because this is what is already being use in auth0-angular, auth0-react and auth0-vue to represent the, almost, identical behavior and we believe consistency is not unimportant, especially to improve DX for people working with both auth0-react and react-native-auth0.

**Pull request merged**
