### PR TITLE
Add back dependabot config for npm

### PR DESCRIPTION
**Pull request by frederikprijck**
### Changes

Adds back dependabot configuration for npm.

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] All existing and new tests complete without errors
- [x] All active GitHub checks have passed

### CODE REVIEW

**Comment by Widcket** [comment]
👋🏼 I wouldn't say it's adding back, that npm config was just never there: https://github.com/auth0/react-native-auth0/commits/master/.github/dependabot.yml

**Comment by frederikprijck** [comment]
@Widcket  I believe it was enabled by default because of the lack of dependabot file. Now that we have the dependabot file, without an npm configuration, we won't be getting dependabot PRs anymore [like we did before](https://github.com/auth0/react-native-auth0/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+author%3Aapp%2Fdependabot). It should only be getting github action updates now.

**Comment by Widcket** [comment]
Thanks, wasn't aware that it was enabled by default (where?).

**Comment by frederikprijck** [comment]
I am not aware where that default is defined, but I noticed dependabot stopped opening PRs once we added this file in different repositories. Once I merged this change in repos like SPA-JS and Angular, dependabot kicked in again.

**Pull request merged**
