### PR TITLE
#256: keep auth network connection open

### PR DESCRIPTION
**Pull request by pcurc**
### Changes

Added the initiation of a background task before starting web authentication flow. This was blatantly borrowed from @georgeloring's work in a [similar PR for react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth/pull/415).

This change was necessary to handle situations where the user had to switch apps in the midst of the authentication process to confirm 2FA (e.g. with Microsoft Authenticator). Previously, the network connection was immediately being closed upon app switch, which prevented the long-running connection from the IdP from being around to acknowledge the 2FA confirmation upon switching back.

### References

Detailed in:
https://github.com/auth0/react-native-auth0/issues/256
https://community.auth0.com/t/unable-to-log-in-with-idp-that-uses-2fa-due-to-app-switch/33674?u=pcurc

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

- [ ] This change adds unit test coverage
- [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] All existing and new tests complete without errors
- [ ] All active GitHub checks have passed

### CODE REVIEW

**Comment by cocojoe** [comment]
@pcurc do you have a video of this issue in action? Thanks

**Comment by pcurc** [comment]
I do not; I could record one, if it's essential to moving the process forward.

**Comment by Widcket** [comment]
Closing due to lack of activity on the source issue https://github.com/auth0/react-native-auth0/issues/256

**Comment by Widcket** [comment]
@pcurc apologies for the delay. Thanks for your contribution!

**Comment by pcurc** [comment]
Thanks to you! Pleased to have helped out and happy this was resolved.

**Pull request merged**
